{
    login: 'qbolt',
    id: 17500092,
    node_id: 'MDQ6VXNlcjE3NTAwMDky',
    avatar_url: 'https: //avatars0.githubusercontent.com/u/17500092?v=4',
    gravatar_id: '',
    url: 'https: //api.github.com/users/qbolt',
    html_url: 'https: //github.com/qbolt',
    followers_url: 'https: //api.github.com/users/qbolt/followers',
    following_url: 'https: //api.github.com/users/qbolt/following{/other_user}',
    gists_url: 'https: //api.github.com/users/qbolt/gists{/gist_id}',
    starred_url: 'https: //api.github.com/users/qbolt/starred{/owner}{/repo}',
    subscriptions_url: 'https: //api.github.com/users/qbolt/subscriptions',
    organizations_url: 'https: //api.github.com/users/qbolt/orgs',
    repos_url: 'https: //api.github.com/users/qbolt/repos',
    events_url: 'https: //api.github.com/users/qbolt/events{/privacy}',
    received_events_url: 'https: //api.github.com/users/qbolt/received_events',
    type: 'User',
    site_admin: false,
    name: 'Quinton Bolt',
    company: 'Cook Systems',
    blog: 'quintonbolt.com',
    location: 'Memphis, TN',
    email: 'bolt.quinton@gmail.com',
    hireable: null,
    bio: 'Designer/Developer',
    public_repos: 17,
    public_gists: 0,
    followers: 4,
    following: 0,
    created_at: '2016-02-26T17: 06: 40Z',
    updated_at: '2018-08-30T23: 38: 09Z'
}